zope:
  environment:
    USERID: '1001'
  domainname: eionet.europa.eu
  labels:
    io.rancher.scheduler.affinity:host_label: hostname=eionet-cph-10
  hostname: planner
  image: eeacms/planner
  volumes:
  - planner-data:/var/local/website/var
  mem_limit: 3221225472
  ports:
  - "8080"
